# Generated by Django 2.0.4 on 2018-08-19 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitflipAnalyzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_challenge', models.IntegerField(default=0, help_text='Enter the challenge as a decimal value and the system will truncate or add zeros to the most significant bit side (e.g., 12 will be converted to 1100 and then padded to 001100 if the PUF has 6 stages)')),
                ('number_of_pufs', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', models.CharField(choices=[('dirac', 'dirac delta (singleton)'), ('normal', 'normal (gaussian)'), ('uniform', 'uniform')], max_length=30)),
                ('mean', models.FloatField(blank=True, default=10.0, null=True)),
                ('sigma', models.FloatField(blank=True, default=0.1, null=True)),
                ('lbound', models.FloatField(blank=True, default=9.9, null=True)),
                ('rbound', models.FloatField(blank=True, default=10.1, null=True)),
            ],
            options={
                'verbose_name': 'Probability Distribution Function',
            },
        ),
        migrations.CreateModel(
            name='PUFGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture', models.CharField(choices=[('loop', 'loop'), ('arbiter', 'arbiter')], max_length=30)),
                ('stages', models.IntegerField(default=10)),
                ('sensitivity', models.FloatField(default=0.0)),
                ('production_pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pufsim.PDF')),
                ('sample_pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_pdf_revacc', to='pufsim.PDF')),
            ],
        ),
        migrations.AddField(
            model_name='bitflipanalyzer',
            name='puf_generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pufsim.PUFGenerator'),
        ),
    ]
