# Generated by Django 2.0.4 on 2018-09-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pufsim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitflipanalyzer',
            name='data',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='bitflipanalyzer',
            name='progress',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
