# Generated by Django 2.0.4 on 2018-09-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pufsim', '0002_auto_20180925_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitflipanalyzer',
            name='pid',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
