# Generated by Django 2.0.4 on 2018-10-09 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pufsim', '0003_bitflipanalyzer_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoBitflipAnalyzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_challenge', models.IntegerField(default=0, help_text='Enter the challenge as a decimal value and the system will truncate or add zeros to the most significant bit side (e.g., 12 will be converted to 1100 and then padded to 001100 if the PUF has 6 stages)')),
                ('test_challenge', models.IntegerField(default=0, help_text='Enter the challenge as a decimal value and the system will truncate or add zeros to the most significant bit side (e.g., 12 will be converted to 1100 and then padded to 001100 if the PUF has 6 stages)')),
                ('number_of_pufs', models.IntegerField(default=100)),
                ('progress', models.IntegerField(default=0, editable=False)),
                ('data', models.TextField(blank=True, editable=False)),
                ('pid', models.IntegerField(default=0, editable=False)),
                ('puf_generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pufsim.PUFGenerator')),
            ],
        ),
    ]
