# Generated by Django 2.0.4 on 2018-11-13 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pufsim', '0005_auto_20181009_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborPredictor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, editable=False)),
                ('data', models.TextField(blank=True, editable=False)),
                ('pid', models.IntegerField(default=0, editable=False)),
                ('distance', models.TextField(choices=[('triangle', 'triangle'), ('beta', 'beta (triangle/2)'), ('hamming', 'hamming')], max_length=30)),
                ('group', models.BooleanField(default=True, help_text='Whether we choose a single closest neighbor or a group of closest neighbors.')),
                ('match_range', models.IntegerField(default=0, help_text='The range of acceptable deviation.')),
                ('known_set_limit', models.IntegerField(default=2, help_text='The predictor will iterate over `n` from 1 to `known_set_limit`, where `n` is the known set size that we use to predict the next challenge.')),
                ('number_of_pufs', models.IntegerField(default=100)),
                ('puf_generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pufsim.PUFGenerator')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
