# Generated by Django 2.1.3 on 2018-11-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pufsim', '0007_auto_20181120_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborpredictor',
            name='distance',
            field=models.TextField(choices=[('gamma', 'gamma'), ('hamming', 'hamming')], default='gamma', max_length=30),
        ),
    ]
