# Generated by Django 2.1.3 on 2018-12-17 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pufsim', '0008_auto_20181127_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitflipanalyzer',
            options={'verbose_name': 'Bitflip Analyzer'},
        ),
        migrations.AlterModelOptions(
            name='challengepairanalyzer',
            options={'verbose_name': 'Challenge Pair Analyzer'},
        ),
        migrations.AlterModelOptions(
            name='neighborpredictor',
            options={'verbose_name': 'Neighbor Predictor'},
        ),
        migrations.AlterModelOptions(
            name='pufgenerator',
            options={'verbose_name': 'PUF Generator'},
        ),
    ]
