# Generated by Django 2.1.3 on 2019-01-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pufsim', '0009_auto_20181217_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborpredictor',
            name='iterations_per_puf',
            field=models.IntegerField(default=100),
        ),
    ]
