# Generated by Django 2.1.3 on 2019-01-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pufsim', '0010_neighborpredictor_iterations_per_puf'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborpredictor',
            name='hop_by_power_of_two',
            field=models.BooleanField(default=False, help_text='Bins go from K to known_set_limit, if this option is checked, then go from 2^(K-1) to 2^(known_set_limit).'),
        ),
        migrations.AlterField(
            model_name='neighborpredictor',
            name='k',
            field=models.IntegerField(default=1, help_text='0 for choose all'),
        ),
    ]
