# Generated by Django 2.1.3 on 2019-02-11 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pufsim', '0011_auto_20190115_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositePUFGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture', models.CharField(choices=[('xor', 'xor')], max_length=30)),
                ('number_of_child_pufs', models.IntegerField(default=10)),
                ('child_architecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pufsim.PUFGenerator')),
            ],
            options={
                'verbose_name': 'Composite PUF Generator',
            },
        ),
    ]
