# Generated by Django 2.1.3 on 2019-03-04 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pufsim', '0012_compositepufgenerator'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiasTester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, editable=False)),
                ('data', models.TextField(blank=True, editable=False)),
                ('pid', models.IntegerField(default=0, editable=False)),
                ('puf_id', models.PositiveIntegerField()),
                ('number_of_pufs', models.IntegerField(default=100)),
                ('n', models.IntegerField(default=100, help_text='How many samples to get for each PUF')),
                ('puf_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'pufsim'), ('model', 'PUFGenerator')), models.Q(('app_label', 'pufsim'), ('model', 'CompositePUFGenerator')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Bias Tester',
            },
        ),
    ]
