# Generated by Django 2.1.3 on 2019-03-26 05:32

from django.db import migrations
import gfklookupwidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pufsim', '0014_auto_20190304_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biastester',
            name='puf_id',
            field=gfklookupwidget.fields.GfkLookupField(),
        ),
    ]
