# Generated by Django 2.1.3 on 2019-03-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pufsim', '0015_auto_20190326_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biastester',
            name='puf_id',
            field=models.PositiveIntegerField(),
        ),
    ]
